module.exports = [
    {
        title: "AIR JORDAN 1 COLLEGE NAVY",
        description: "Las Air Jordan 1 High '85 vuelven en piel premium con el estilo y la forma de las originales, pero en la combinación de colores \"College Navy\" para rendir homenaje al partido universitario que Michael jugó aquel día. Celebra el 40 aniversario de esta victoria que le llevó a conseguir un título frente a la Universidad de Georgetown con este icono original.",
        price: 189.99,
        moneda: "Euros",
        stock: 15,
        img: "https://media.revistagq.com/photos/61d81e540e7194d74bb5d1cd/3:2/w_1986,h_1324,c_limit/Captura%20de%20pantalla%202022-01-07%20a%20las%2012.04.43.png",
    },
    {
        title: "REEBOK CLUB C 85 DE TYRRELL WINSTON",
        description: "Tanto la Club C como la Question Mid de Reebok x Tyrrell Winston cuentan con detalles de pelo de poni que representan el transporte tradicional a caballo, su firma y sus famosos Noodles, los garabatos inspirados en Nueva York que hacen un guiño a su obra y simbolizan el metro y los medios de transporte modernos.",
        price: 200,
        moneda: "USD",
        stock: 30,
        img: "https://media.revistagq.com/photos/62037f397fb15066e7106618/master/w_1600%2Cc_limit/1_tyrrell-winston-reebok-club-c-85.jpeg",
    },
    {
        title: "Off-White x Nike Dunk Low",
        description: "El Off-White x Nike Dunk Low \"University Gold\" es uno de los tres colores exclusivos del remix de Virgil Abloh de la zapatilla clásica. Después de colaborar en una gran cantidad de modelos Nike de archivo, Abloh aplica su oficio a un favorito personal suyo al equipar al Dunk con algunas actualizaciones únicas.",
        price: 180,
        moneda: "Euros",
        stock: 10,
        img: "https://images.stockx.com/images/Nike-Dunk-Low-Off-White-Lot-32-Product.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&q=90&dpr=2&trim=color&updated_at=1629211257",
    },
    {
        title: "CG x Rockstud X de Valentino Garavani",
        description: "",
        price: "",
        moneda: "Euros",
        stock: 34,
        img: "",
    },
    {
        title: "New Balance 47/50 x Staud",
        description: "",
        price: "",
        moneda: "Euros",
        stock: 40,
        img: "",
    },
    {
        title: "Adidas Forum Buckle Low x Bad Bunny",
        description: "",
        price: 3,
        moneda: "Euros",
        stock: 5,
        img: "",
    },
    {
        title: "Nike Air Force 1 x Louis Vuitton",
        description: "",
        price: 2500,
        moneda: "Euros",
        stock: 1,
        img: "https://media.revistagq.com/photos/6204e090e1380e1a1cb03321/16:9/w_2560%2Cc_limit/Louis%2520Vuitton%2520y%2520Nike%2520Air%2520Force%25201%2520por%2520Virgil%2520Abloh%2520(2).jpg",
    },
]